# Generated by Django 5.1.3 on 2024-11-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('specialization', models.CharField(blank=True, max_length=50, verbose_name='Специализация')),
                ('photo', models.ImageField(upload_to='photos_for_people/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=32, verbose_name='Название команды')),
                ('team_photo', models.ImageField(blank=True, upload_to='photos_for_teams/', verbose_name='Фотография команды')),
                ('members', models.ManyToManyField(related_name='commands', to='website.person', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo_before', models.ImageField(blank=True, upload_to='photos_for_posts/', verbose_name='Фото до')),
                ('photo_after', models.ImageField(blank=True, upload_to='photos_for_posts/', verbose_name='Фото после')),
                ('cover_photo', models.ImageField(blank=True, upload_to='photos_for_posts/', verbose_name='Обложка')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='website.command', verbose_name='Команда создателей')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
